version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: eeg_redis
    ports:
      - "7777:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  rq-dashboard:
    image: eoranged/rq-dashboard
    container_name: eeg_rq_dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis_data: